[package]
name = "linux-procfs"
version = "0.3.16"
authors = ["aki <aki.akaguma@hotmail.com>"]
description = """
The linux-procfs is the data snap library for the `/proc/` filesystem on the linux os.
"""
keywords = ["procfs"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.58.0"
repository = "https://github.com/aki-akaguma/linux-procfs"

[dependencies]
naive_opt = "0.1"
memx = "0.1"
cfg-iif = "0.2"

[dev-dependencies]

[build-dependencies]

[features]
default = ["minimum"]
minimum = ["has_stat_min", "has_meminfo_min", "has_vmstat_min",
    "has_diskstats_min", "has_netdevs_min", "has_pidentry_min"]
mean = ["has_stat_some", "has_meminfo_some", "has_vmstat_some",
    "has_diskstats_some", "has_netdevs_some", "has_pidentry_some"]
maximum = ["has_stat_all", "has_meminfo_all", "has_vmstat_all",
    "has_diskstats_all", "has_netdevs_all", "has_pidentry_all"]

has_stat_min = []
has_stat_some = []
has_stat_all = ["has_stat_btime", "has_stat_procs_running", "has_stat_procs_blocked"]
has_stat_btime = []
has_stat_procs_running = []
has_stat_procs_blocked = []

has_meminfo_min = []
has_meminfo_some = []
has_meminfo_all = [
    "has_meminfo_mem_available", "has_meminfo_active_anon", "has_meminfo_inactive_anon",
    "has_meminfo_active_file", "has_meminfo_inactive_file", "has_meminfo_unevictable",
    "has_meminfo_mlocked", "has_meminfo_high_total", "has_meminfo_high_free",
    "has_meminfo_low_total", "has_meminfo_low_free", "has_meminfo_mmap_copy",
    "has_meminfo_dirty", "has_meminfo_writeback", "has_meminfo_anon_pages",
    "has_meminfo_mapped", "has_meminfo_slab", "has_meminfo_slab_reclaimable",
    "has_meminfo_slab_unreclaim", "has_meminfo_page_tables",
    "has_meminfo_nfs_unstable", "has_meminfo_bounce", "has_meminfo_commit_limit",
    "has_meminfo_commit_as", "has_meminfo_vmalloc_total", "has_meminfo_vmalloc_used",
    "has_meminfo_vmalloc_chunk"
]
has_meminfo_mem_available = []
has_meminfo_active_anon = []
has_meminfo_inactive_anon = []
has_meminfo_active_file = []
has_meminfo_inactive_file = []
has_meminfo_unevictable = []
has_meminfo_mlocked = []
has_meminfo_high_total = []
has_meminfo_high_free = []
has_meminfo_low_total = []
has_meminfo_low_free = []
has_meminfo_mmap_copy = []

has_meminfo_dirty = []
has_meminfo_writeback = []
has_meminfo_anon_pages = []
has_meminfo_mapped = []
has_meminfo_slab = []
has_meminfo_slab_reclaimable = []
has_meminfo_slab_unreclaim = []
has_meminfo_page_tables = []
has_meminfo_nfs_unstable = []
has_meminfo_bounce = []
has_meminfo_commit_limit = []
has_meminfo_commit_as = []
has_meminfo_vmalloc_total = []
has_meminfo_vmalloc_used = []
has_meminfo_vmalloc_chunk = []

has_vmstat_min = []
has_vmstat_some = []
has_vmstat_all = [
    "has_vmstat_nr_free_pages", "has_vmstat_nr_active", "has_vmstat_nr_inactive",
    
    "has_vmstat_nr_anon_pages", "has_vmstat_nr_mapped", "has_vmstat_nr_file_pages",
    "has_vmstat_nr_slab", "has_vmstat_nr_slab_reclaimable", "has_vmstat_nr_slab_unreclaimable",
    "has_vmstat_nr_page_table_pages", "has_vmstat_nr_dirty", "has_vmstat_nr_writeback",
    "has_vmstat_nr_unstable", "has_vmstat_nr_bounce", "has_vmstat_nr_vmscan_write",
    "has_vmstat_nr_writeback_temp",

    "has_vmstat_numa_hit", "has_vmstat_numa_miss", "has_vmstat_numa_foreign",
    "has_vmstat_numa_interleave", "has_vmstat_numa_local",

    "has_vmstat_pgalloc", "has_vmstat_pgfree", "has_vmstat_pgactivate", "has_vmstat_pgdeactivate",
    "has_vmstat_pgfault", "has_vmstat_pgmajfault", "has_vmstat_pgrefill",
    "has_vmstat_pgsteal", "has_vmstat_pgscan_kswapd", "has_vmstat_pgscan_direct",
    "has_vmstat_pginodesteal", "has_vmstat_slabs_scanned", "has_vmstat_kswapd_steal",
    "has_vmstat_kswapd_inodesteal", "has_vmstat_pageoutrun", "has_vmstat_allocstall",
    "has_vmstat_pgrotated", "has_vmstat_htlb_buddy_alloc"
]
has_vmstat_nr_free_pages = []
has_vmstat_nr_active = []
has_vmstat_nr_inactive = []

has_vmstat_nr_anon_pages = []
has_vmstat_nr_mapped = []
has_vmstat_nr_file_pages = []
has_vmstat_nr_slab = []
has_vmstat_nr_slab_reclaimable = []
has_vmstat_nr_slab_unreclaimable = []
has_vmstat_nr_page_table_pages = []
has_vmstat_nr_dirty = []
has_vmstat_nr_writeback = []
has_vmstat_nr_unstable = []
has_vmstat_nr_bounce = []
has_vmstat_nr_vmscan_write = []
has_vmstat_nr_writeback_temp = []

has_vmstat_numa_hit = []
has_vmstat_numa_miss = []
has_vmstat_numa_foreign = []
has_vmstat_numa_interleave = []
has_vmstat_numa_local = []
has_vmstat_numa_other = []

has_vmstat_pgalloc = []

has_vmstat_pgfree = []
has_vmstat_pgactivate = []
has_vmstat_pgdeactivate = []

has_vmstat_pgfault = []
has_vmstat_pgmajfault = []

has_vmstat_pgrefill = []
has_vmstat_pgsteal = []
has_vmstat_pgscan_kswapd = []
has_vmstat_pgscan_direct = []

has_vmstat_pginodesteal = []
has_vmstat_slabs_scanned = []
has_vmstat_kswapd_steal = []
has_vmstat_kswapd_inodesteal = []
has_vmstat_pageoutrun = []
has_vmstat_allocstall = []

has_vmstat_pgrotated = []
has_vmstat_htlb_buddy_alloc = []

has_diskstats_min = []
has_diskstats_some = []
has_diskstats_all = [
    "has_diskstats_device_number", "has_diskstats_running", "has_diskstats_use"
]
has_diskstats_device_number = []
has_diskstats_running = []
has_diskstats_use = []

has_netdevs_min = []
has_netdevs_some = []
has_netdevs_all = [
    "has_netdevs_rx_errors", "has_netdevs_rx_dropped_errors", "has_netdevs_rx_fifo_errors",
    "has_netdevs_rx_frame_errors", "has_netdevs_rx_compressed", "has_netdevs_rx_multicast",
    "has_netdevs_tx_errors", "has_netdevs_tx_dropped_errors", "has_netdevs_tx_fifo_errors",
    "has_netdevs_tx_collisions", "has_netdevs_tx_carrier_errors", "has_netdevs_tx_compressed"
]
has_netdevs_rx_errors = []
has_netdevs_rx_dropped_errors = []
has_netdevs_rx_fifo_errors = []
has_netdevs_rx_frame_errors = []
has_netdevs_rx_compressed = []
has_netdevs_rx_multicast = []

has_netdevs_tx_errors = []
has_netdevs_tx_dropped_errors = []
has_netdevs_tx_fifo_errors = []
has_netdevs_tx_collisions = []
has_netdevs_tx_carrier_errors = []
has_netdevs_tx_compressed = []

has_pidentry_min = ["has_pidentry_stat_min", "has_pidentry_status_min"]
has_pidentry_some = ["has_pidentry_stat_some", "has_pidentry_status_some"]
has_pidentry_all = ["has_pidentry_stat_all", "has_pidentry_status_all"]

has_pidentry_stat_min = []
has_pidentry_stat_some = [
    "has_pidentry_stat_comm", "has_pidentry_stat_state", "has_pidentry_stat_vsize",
    "has_pidentry_stat_rss", "has_pidentry_stat_delayacct"
]
has_pidentry_stat_all = [
    "has_pidentry_stat_comm", "has_pidentry_stat_state", "has_pidentry_stat_session",
    "has_pidentry_stat_tty_nr", "has_pidentry_stat_tpgid", "has_pidentry_stat_flags",
    "has_pidentry_stat_minflt", "has_pidentry_stat_cminflt",
    "has_pidentry_stat_majflt", "has_pidentry_stat_cmajflt",
    "has_pidentry_stat_priority", "has_pidentry_stat_vsize", "has_pidentry_stat_rss",
    "has_pidentry_stat_rlim", "has_pidentry_stat_startcode", "has_pidentry_stat_endcode",
    "has_pidentry_stat_startstack", "has_pidentry_stat_kstesp", "has_pidentry_stat_ksteip",
    "has_pidentry_stat_signal", "has_pidentry_stat_blocked", "has_pidentry_stat_sigignore",
    "has_pidentry_stat_sigcatch",
    "has_pidentry_stat_exit_signal", "has_pidentry_stat_processor", "has_pidentry_stat_rt_priority",
    "has_pidentry_stat_policy", "has_pidentry_stat_delayacct"
]
has_pidentry_stat_comm = []
has_pidentry_stat_state = []
has_pidentry_stat_session = []
has_pidentry_stat_tty_nr = []
has_pidentry_stat_tpgid = []
has_pidentry_stat_flags = []
has_pidentry_stat_minflt = []
has_pidentry_stat_cminflt = []
has_pidentry_stat_majflt = []
has_pidentry_stat_cmajflt = []
has_pidentry_stat_priority = []
has_pidentry_stat_vsize = []
has_pidentry_stat_rss = []
has_pidentry_stat_rlim = []
has_pidentry_stat_startcode = []
has_pidentry_stat_endcode = []
has_pidentry_stat_startstack = []
has_pidentry_stat_kstesp = []
has_pidentry_stat_ksteip = []
has_pidentry_stat_signal = []
has_pidentry_stat_blocked = []
has_pidentry_stat_sigignore = []
has_pidentry_stat_sigcatch = []
has_pidentry_stat_exit_signal = []
has_pidentry_stat_processor = []
has_pidentry_stat_rt_priority = []
has_pidentry_stat_policy = []
has_pidentry_stat_delayacct = []

has_pidentry_status_min = []
has_pidentry_status_some = []
has_pidentry_status_all = [
    "has_pidentry_status_name", "has_pidentry_status_state",
    "has_pidentry_status_tgid", "has_pidentry_status_ngid", "has_pidentry_status_tracer_pid",
    "has_pidentry_status_vm_peak", "has_pidentry_status_vm_pin", "has_pidentry_status_vm_hwm",
    "has_pidentry_status_rss_anon", "has_pidentry_status_rss_file", "has_pidentry_status_rss_shmem",
    "has_pidentry_status_vm_pmd"
]
has_pidentry_status_name = []
has_pidentry_status_state = []
has_pidentry_status_tgid = []
has_pidentry_status_ngid = []
has_pidentry_status_tracer_pid = []
has_pidentry_status_vm_peak = []
has_pidentry_status_vm_pin = []
has_pidentry_status_vm_hwm = []
has_pidentry_status_rss_anon = []
has_pidentry_status_rss_file = []
has_pidentry_status_rss_shmem = []
has_pidentry_status_vm_pmd = []
